apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-snofi-backend-logs-{{ .Values.global.project }}
spec:
  storageClassName: efs-sc-{{ .Values.global.project }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi